application: tj-shs
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/mail/.+
  script: handle_incoming_anuncio.app
  login: admin
- url: /_ah/bounce
  script: handle_bounced_anuncio.app
  login: admin
- url: /asistencia
  static_dir: asistencia
  application_readable: true
- url: /horas
  static_dir: horas
  application_readable: true
- url: /cositas
  static_dir: cositas
  application_readable: true
- url: /.*
  script: shs_website.app

inbound_services:
- mail
- mail_bounce

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest